name: Build snapshot

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build and publish with gradle
        run: ./gradlew publish